name: Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      RESAS_API_KEY:  ${{ secrets.RESAS_API_KEY }}


    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: npm ci
      - run: npm run build

      - run: npx netlify-cli deploy --dir=build --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
